version: "1.0"

services:

  langchain-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: langchain
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    network_mode: bridge
